# import = [
# "~/config/alacritty/keybindings.toml"
# ]

[env]
TERM = "xterm-256color"

[scrolling]
history = 100000

[cursor]
style = { shape = "Block", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "Off"}

[mouse]
hide_when_typing = true
