#!/bin/zsh

export EDITOR="emacs -nw --init-directory=~/.config/emacs/slim"
export VISUAL="emacs -nw --init-directory=~/.config/emacs/slim"
export SUDO_EDITOR="$EDITOR"
eval "$(/opt/homebrew/bin/brew shellenv)"
