#!/bin/zsh

PROMPT='%~ %# '

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias l="less"
alias reload="source ~/.zshrc"

# emacs
alias emacs="emacs -nw"
alias e="emacs -nw --init-directory=~/.config/emacs/slim"

# history
# https://postgresqlstan.github.io/cli/zsh-history-options/
HISTSIZE=100000
SAVEHIST=10000
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_NO_STORE
setopt HIST_REDUCE_BLANKS
setopt HIST_VERIFY
setopt INC_APPEND_HISTORY

# docker
alias dc="docker container"
alias dl="docker logs -fn0"

# tmux
alias tt="tmux new-session"
alias ts="tmux new-session -A -s" # [session-name]
alias tk="tmux kill-session -t" # [session-name]
alias ta="tmux attach" # attach to last session
alias tls="tmux list-sessions"

# fzf
alias f="fzf"
source <(fzf --zsh)

# guile
export GUILE_LOAD_PATH="/opt/homebrew/share/guile/site/3.0"
export GUILE_LOAD_COMPILED_PATH="/opt/homebrew/lib/guile/3.0/site-ccache"
export GUILE_SYSTEM_EXTENSIONS_PATH="/opt/homebrew/lib/guile/3.0/extensions"

# golang
. ~/.asdf/plugins/golang/set-env.zsh

# asdf
export ASDF_DIR="$HOME/.asdf"
export PATH="$ASDF_DIR/shims:$PATH"

# editor integration
export EDITOR="nvim"
export GPG_TTY=$(tty) # used for gpg signing
