#!/bin/zsh

PROMPT='%~ %# '

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

alias top="btop"
alias emacs="emacs -nw"

# history
# https://postgresqlstan.github.io/cli/zsh-history-options/
HISTSIZE=100000
SAVEHIST=10000
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_NO_STORE
setopt HIST_REDUCE_BLANKS
setopt HIST_VERIFY
setopt INC_APPEND_HISTORY

# fzf
source <(fzf --zsh)

# guile
export GUILE_LOAD_PATH="/opt/homebrew/share/guile/site/3.0"
export GUILE_LOAD_COMPILED_PATH="/opt/homebrew/lib/guile/3.0/site-ccache"
export GUILE_SYSTEM_EXTENSIONS_PATH="/opt/homebrew/lib/guile/3.0/extensions"

# golang
. ~/.asdf/plugins/golang/set-env.zsh

# asdf
export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"
. $(brew --prefix asdf)/libexec/asdf.sh
