# https://docs.helix-editor.com/title-page.html

theme = "rose_pine"

[editor]
line-number = "relative"
mouse = true
# cursorline = true
rulers = [100]
# bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[editor.indent-guides]
render = false

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position", "file-encoding", "version-control"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space]
F = "file_picker_in_current_buffer_directory"

[keys.normal.g]
c = ":open ~/.config/helix/config.toml"
