require:
    # - rubocop-minitest
    - rubocop-rails
    # - rubocop-factory_bot
    # - rubocop-thread_safety
    # - rubocop-rake
    # - rubocop-performance

AllCops:
    SuggestExtensions: false
    Exclude:
        - "test/**/*.rb"
        - "spec/**/*.rb"

Style/Documentation:
    Enabled: No

Style/FrozenStringLiteralComment:
    Enabled: No

Style/StringLiterals:
    EnforcedStyle: single_quotes # default

Style/StringLiteralsInInterpolation:
    EnforcedStyle: single_quotes # default

Layout/MultilineOperationIndentation:
    EnforcedStyle: aligned # default

Layout/MultilineMethodCallIndentation:
    EnforcedStyle: indented_relative_to_receiver

Layout/LineLength:
    Max: 100 # default is 120

Metrics/CyclomaticComplexity:
    Max: 9 # default is 7

Metrics/MethodLength:
    Max: 25 # default is 10

Metrics/ClassLength:
    Max: 150 # default is 100

Metrics/AbcSize:
    Enabled: No # too annoying
