#!/bin/zsh

autoload -U colors && colors

autoload -U select-word-style
select-word-style bash

bindkey -e # emacs mode

# NOTE: Do not set TERM, conflicts with Eat-Integration

EDITOR="emacs"
NEWLINE=$'\n'
PROMPT="%B%{$(tput setaf 220)%}%n @ %~$NEWLINE\$%b "
SUDO_EDITOR="$EDITOR"
TIMEFMT=$'%J\n%U user\n%S system\n%P cpu\n%*E total'
VISUAL="emacs"

export ASDF_DIR="$HOME/.asdf"
export GPG_TTY=$(tty)
export GOPATH="$HOME/go"
export PATH="$ASDF_DIR/shims:$PATH"
export PATH="$GOPATH/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

alias ....='cd ../../..'
alias ...='cd ../..'
alias ..='cd ..'
alias e="emacs -nw"
alias emacs="emacs -nw"
alias grep="grep --line-buffered --color"
alias l="less"
alias lg="lazygit"
alias ll="ls -lh --color"
alias reload="source ~/.zshrc"
alias rgrep="grep --color -rnIi"
alias top="btop"

[ -n "$EAT_SHELL_INTEGRATION_DIR" ] && source "$EAT_SHELL_INTEGRATION_DIR/zsh"

eval "$(direnv hook zsh)"

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="eastwood"
ZOXIDE_CMD_OVERRIDE="cd"
GIT_AUTO_FETCH_INTERVAL=1200
plugins=(aws docker docker-compose encode64 fzf git git-auto-fetch zoxide)
source $ZSH/oh-my-zsh.sh
