---
include:
  - "**/*.rb"
exclude:
  - spec/**/*
  - "**/*_spec.rb"
  - test/**/*
  - "**/*_test.rb"
  - vendor/**/*
  - ".bundle/**/*"
require: []
domains: []
reporters:
  - rubocop
  #- require_not_found
  - typecheck
  - update_errors
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths: []
plugins:
  - solargraph-rails
max_files: 10000
