;;; -*- lexical-binding: t -*-

(use-package color-theme-sanityinc-tomorrow :defer t)
(use-package creamsody-theme :defer t)
(use-package doric-themes :defer t)
(use-package ef-themes :defer t)
(use-package gruber-darker-theme :defer t)
(use-package gruvbox-theme :defer t)
(use-package modus-themes :defer t)
(use-package nano-theme :defer t)
(use-package solarized-theme :defer t)
(use-package kuronami-theme :defer t)
(use-package standard-themes :defer t)
(use-package timu-rouge-theme :defer t)
(use-package zenburn-theme :defer t)
