vim.keymap.set('n', '<leader>op', '<cmd>NvimTreeFindFile<cr>', { desc = 'Open file explorer' })
vim.keymap.set('n', '<leader>tp', '<cmd>NvimTreeFindFileToggle<cr>', { desc = 'Toggle file explorer' })
vim.keymap.set('i', '<f12>', "<cmd>WhichKey '' i<cr>", { desc = 'Show Top Level WhichKey' })
vim.keymap.set('n', '<C-Enter>', 'i<Enter><Esc>', { desc = 'New line' })
vim.keymap.set('n', '<C-d>', '<C-d>zz', { desc = 'Page down' })
vim.keymap.set('n', '<C-h>', '<C-w>h', { desc = 'Jump left' })
vim.keymap.set('n', '<C-j>', '<C-w>j', { desc = 'Jump down' })
vim.keymap.set('n', '<C-k>', '<C-w>k', { desc = 'Jump up' })
vim.keymap.set('n', '<C-l>', '<C-w>l', { desc = 'Jump right' })
vim.keymap.set('n', '<C-u>', '<C-u>zz', { desc = 'Page up' })
vim.keymap.set('n', '<f12>', '<cmd>WhichKey<cr>', { desc = 'Show Top Level WhichKey' })
vim.keymap.set('n', '<leader><leader>', '<cmd>Telescope find_files<cr>', { desc = 'Find file' })
vim.keymap.set('n', '<leader>@', 'q', { desc = 'Record macro' })
vim.keymap.set('n', '<leader>cY', '<cmd>let @+ = expand("%")<cr>', { desc = "Copy relative filepath" })
vim.keymap.set('n', '<leader>ca', vim.lsp.buf.code_action, { desc = 'Action' })
vim.keymap.set('n', '<leader>cy', '<cmd>let @+ = expand("%:t")<cr>', { desc = "Copy filename" })
vim.keymap.set('n', '<leader>f.', '<cmd>Telescope file_browser path=%:p:h select_buffer=true<cr>', { desc = 'Find (cwd) file' })
vim.keymap.set('n', '<leader>f:', '<cmd>Telescope commands<cr>', { desc = 'Find command' })
vim.keymap.set('n', '<leader>f>', '<cmd>Telescope file_browser select_buffer=true<cr>', { desc = 'Find (root) file' })
vim.keymap.set('n', '<leader>fB', '<cmd>Telescope buffers only_cwd=false sort_mru=true<cr>', { desc = 'Find (all) buffer' })
vim.keymap.set('n', '<leader>fP', '<cmd>Telescope project<cr>', { desc = 'Find project' })
vim.keymap.set('n', '<leader>fR', '<cmd>Telescope oldfiles only_cwd=false<cr>', { desc = 'Find (all) recent file' })
vim.keymap.set('n', '<leader>fa', '<cmd>Telescope find_files follow=true no_ignore=true hidden=true<cr>', { desc = 'Find (all) file' })
vim.keymap.set('n', '<leader>fb', '<cmd>Telescope buffers only_cwd=true sort_mru=true<cr>', { desc = 'Find (cwd) buffer' })
vim.keymap.set('n', '<leader>fd', '<cmd>Telescope diagnostics bufnr=0<cr>', { desc = 'Find diagnostics' })
vim.keymap.set('n', '<leader>ff', '<cmd>Telescope find_files<cr>', { desc = 'Find file' })
vim.keymap.set('n', '<leader>fS', '<cmd>Telescope grep_string<cr>', { desc = 'Find grep search' })
vim.keymap.set('n', '<leader>fh', '<cmd>Telescope help_tags<cr>', { desc = 'Find help tag' })
vim.keymap.set('n', '<leader>fm', '<cmd>Telescope marks<cr>', { desc = 'Find mark' })
vim.keymap.set('n', '<leader>fp', require("auto-session.session-lens").search_session, { desc = 'Find session' })
vim.keymap.set('n', '<leader>fr', '<cmd>Telescope oldfiles only_cwd=true<cr>', { desc = 'Find (cwd) recent file' })
vim.keymap.set('n', '<leader>fs', '<cmd>Telescope live_grep<cr>', { desc = 'Find live search' })
vim.keymap.set('n', '<leader>fz', '<cmd>Telescope current_buffer_fuzzy_find <cr>', { desc = 'Find in current buffer' })
vim.keymap.set('n', '<leader>gB', '<cmd>G blame<cr>', { desc = 'Git blame buffer' })
vim.keymap.set('n', '<leader>gb', function() package.loaded.gitsigns.blame_line { full = true } end, { desc = 'Git blame line' })
vim.keymap.set('n', '<leader>gfL', '<cmd>Telescope git_commits<cr>', { desc = 'Find commit' })
vim.keymap.set('n', '<leader>gfb', '<cmd>Telescope git_branches<cr>', { desc = 'Find branch' })
vim.keymap.set('n', '<leader>gfl', '<cmd>Telescope git_bcommits<cr>', { desc = 'Find buffer commit' })
vim.keymap.set('n', '<leader>gfz', '<cmd>Telescope git_stash<cr>', { desc = 'Find stash' })
vim.keymap.set('n', '<leader>gg', '<cmd>Git<cr>', { desc = 'Git status' })
vim.keymap.set('n', '<leader>ot', '<cmd>belowright split | resize 15 | terminal<cr>', { desc = 'Open terminal' })
vim.keymap.set('n', '<leader>tD', ":lua =(vim.diagnostic.is_disabled() and (vim.diagnostic.enable() or 'enabled')) or vim.diagnostic.disable() or 'disabled'<cr>", { desc = 'Toggle global diagnostics' })
vim.keymap.set('n', '<leader>td', ":lua =(vim.diagnostic.is_disabled(0) and (vim.diagnostic.enable(0) or 'enabled')) or vim.diagnostic.disable(0) or 'disabled'<cr>", { desc = 'Toggle buffer diagnostics' })
vim.keymap.set('n', '<leader>tu', '<cmd>UndotreeToggle<cr>', { desc = 'Toggle undo tree' })
vim.keymap.set('n', 'K', vim.lsp.buf.hover, { desc = 'Hover' })
vim.keymap.set('n', 'Q', '<nop>')
vim.keymap.set('n', '[d', vim.diagnostic.goto_prev, { desc = 'Prev diagnostics' })
vim.keymap.set('n', ']d', vim.diagnostic.goto_next, { desc = 'Next diagnostics' })
vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, { desc = 'Go to declaration' })
vim.keymap.set('n', 'gd', vim.lsp.buf.definition, { desc = 'Go to definition' })
vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, { desc = 'Implementation' })
vim.keymap.set('n', 'go', vim.diagnostic.open_float, { desc = 'Open diagnostics' })
vim.keymap.set('n', 'gr', vim.lsp.buf.references, { desc = 'References' })
vim.keymap.set('n', 'gs', vim.lsp.buf.signature_help, { desc = 'Signature' })
vim.keymap.set('n', 'q', '<Esc>')
vim.keymap.set('n', 'q:', '<nop>')
vim.keymap.set('t', '<Esc>', '<C-\\><C-n>', { desc = 'Exit terminal mode' })
vim.keymap.set('v', '<f12>', "<cmd>WhichKey '' v<cr>", { desc = 'Show Top Level WhichKey' })
vim.keymap.set('v', 'J', ':m \'>+1<cr>gv=gv', { desc = 'Move selection down' })
vim.keymap.set('v', 'K', ':m \'<-2<cr>gv=gv', { desc = 'Move selection up' })
vim.keymap.set({ 'i', 'c' }, '<C-a>', '<Home>', { desc = 'Beginning of line' })
vim.keymap.set({ 'i', 'c' }, '<C-e>', '<End>', { desc = 'End of line' })
vim.keymap.set({ 'n', 'v' }, '<leader>fw', '<cmd>Telescope grep_string<cr>', { desc = 'Find word' })
vim.keymap.set({'n', 'v'}, '<leader>cf', vim.lsp.buf.format, { desc = 'Format' })
