#!/bin/bash

PS1="\w \$ " #bash
PROMPT='%~ %# ' #zsh

alias emacs="emacs-nox" # or emacs-nw
alias e="emacs-nox" # or emacs-nw

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# Recommended bash tools to install
alias top="btop"
